version: '3.7'
services:
  mysql:
    image: "mysql:5.7.27"
    ports:
      - "3306:3306"
    volumes:
      - "db-data:/var/lib/mysql"
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      - MYSQL_ROOT_PASSWORD=8VNHNkphA6hvkqDT
      - MYSQL_USER=hand6wecUHdR2jQA
      - MYSQL_PASSWORD=8VNHNkphA6hvkqDT
      - MYSQL_DATABASE=employees
    container_name: mysql

volumes:
  db-data: {}